# Generated by assistant to add title field to Review
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
    ]
